# tomcat
server:
  port: 9091
spring:
  application:
    name: backup
# backup datasource
mango:
  backup:
    datasource:
      host: localhost
      userName: root
      password: 123456
      database: mango